### PR TITLE
437 create send user invite resolver

### LINKED ISSUE #437: Create sendUserInvite resolver that creates a UserInvite row
## Summary:
We want to create a new resolver (or update it if it already exists from #438) which it creates a user invite record in our database, and sends an invite link to the invited email at `https://sistering-dev.web.app/create-account?token={new user invite row record id}`. This makes it so we can securely generate and send out user invites to users from our admin platform.

## Technical:
- Create a `sendUserInvite` resolver in the `userResolver`
- Add types as required by the new `sendUserInvite` resolver, the inputs to the query should be a `email: string` and `role: UserRole`
- For this ticket, just ensure to create the user invite record in the database and return the entity, you do not need to handle sending out emails
- Return new entity created 
- You will need to create a new prisma method in the userService to interact with the DB to create rows.

### PR DESCRIPTION
**Pull request by eevanwong**
## Ticket link
Closes #437 

## Implementation description
* Created resolver that handles creation of userInvite row.

## Steps to test
1. Go to graphql playground
2. Use this mutation:
```
mutation testCreateUserInvite($email: String!) {
  createUserInvite(email: $email, role: VOLUNTEER) {
    pid
    email
    role
  }
}
```

It should respond with the newly created row.

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by neelismail01 — APPROVED** [review]
Looks good to me!

**Review by AdrianaCeric — COMMENTED** [review]
Yo there are some lint errors! Run `yarn fix`!

**Review by MatoPlus — APPROVED** [review]
This is great. Thanks for jamming this out.

**Review by MatoPlus — COMMENTED** [review]
besides the nit Adriana pointed out, this looks good to ship

**Review by MatoPlus — APPROVED** [review]
ship it

**Pull request merged**
