### PR TITLE
Implement type safe error handling

### LINKED ISSUE #99: Type-safe error handling in backend
## User Story and Context

Currently, all of the catch blocks in the backend are not type-safe in that the catch clause variables are implicitly typed as `any`. This is an error case that VS Code highlights. We should instead type them as `unknown` and properly check type before accessing error messages.

TypeScript docs for reference: https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#unknown-on-catch

## Acceptance Criteria

* There is a utility function called `getErrorMessage` in `backend/utilities/errorUtils.ts`
```ts
/* eslint-disable-next-line import/prefer-default-export */
export const getErrorMessage = (error: unknown): string => {
  return error instanceof Error ? error.message : "Unknown error occurred.";
};
```
* All catch clause variables in the backend should be typed as `unknown`, and the error message should be accessed with the `getErrorMessage` function, for example:
```ts
catch (error: unknown) {
  Logger.error(
    `Failed to get entities. Reason = ${getErrorMessage(error)}`,
  );
  throw error;
}
```

## Dev Notes
* N/A

### PR DESCRIPTION
**Pull request by lambo-liu**
## Ticket link

Closes #99 

## Implementation description
* Added a `getErrorMessage` utility function
* Replace all errors with type `unknown`
* Replaced current Logger messages to use `getErrorMessage`

## Steps to test
1. Make sure that application runs as expected and errors are being logged properly

## What should reviewers focus on?
* Didn't miss any errors to be replaced

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by sherryhli — CHANGES_REQUESTED** [review]
There are some cases where the error is being explicitly typed as `any`, do you mind addressing those too? They're flagged by the linter github actions workflow.

The rest looks good!

**Comment by lambo-liu** [comment]
> There are some cases where the error is being explicitly typed as `any`, do you mind addressing those too? They're flagged by the linter github actions workflow.
> 
> The rest looks good!

Just fixed this up. 🔨 

Should we do anything about the `firebaseError` and `postgresError` error types? They are currently marked as type `any`.

**Comment by sherryhli** [comment]
> Should we do anything about the firebaseError and postgresError error types? They are currently marked as type any.

@lambo-liu Yes, let's type them as `unknown` as well

**Comment by lambo-liu** [comment]
> > Should we do anything about the firebaseError and postgresError error types? They are currently marked as type any.
> 
> @lambo-liu Yes, let's type them as `unknown` as well

@sherryhli Should be good now! Let me know if there is anything else we need to patch up 🪡

**Review by sherryhli — APPROVED** [review]
:shipit:

**Pull request merged**
