### PR TITLE
Fix timezone bug in VolunteerPendingShiftsTableRow

### PR DESCRIPTION
**Pull request by sherryhli**
## Ticket link

N/A - quick fix for this issue:
Capture

## Implementation description
* Interpret date in UTC instead of local time in `formatDateMonthDay` util function used in `VolunteerPendingShiftsTableRow`

## Steps to test
1. Login as a volunteer who has pending shifts
2. Verify that the displayed deadline date of the pending shift's associated posting matches what is returned by the backend
Capture1

## What should reviewers focus on?
* N/A

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by MatoPlus — APPROVED** [review]
LGTM. Good catch. I think we still have a few timezone bugs in our app, especially with edge cases for same-day comparisons.

**Review by MatoPlus — COMMENTED** [review]
I think this may have also closed #620, I'll need to test it out.

Edit: Nvm, I don't think it did

**Comment by sherryhli** [comment]
> I think this may have also closed #620, I'll need to test it out.
> 
> Edit: Nvm, I don't think it did but it's fine.

The pending shifts row is currently is the only usage of the `formatDateMonthDay` function so the cause must be something else

**Comment by sherryhli** [comment]
> I think we still have a few timezone bugs in our app, especially with edge cases for same-day comparisons.

Definitely possible, another bug bash could be helpful

**Pull request merged**
