### PR TITLE
Remove employee title from schema

### LINKED ISSUE #452: remove employee title field
update `schema.prisma` to remove the title column from the employee table, then create a migration using `npx prisma migrate dev --name remove_employee_title_field --create-only`

remove any reference to the old employee title field in the backend and frontend

### PR DESCRIPTION
**Pull request by twilkhoo**
## Ticket link

Closes #452 

## Implementation description
* Removed the employee title field from `schema.prisma`
* Ran the migration, in turn generating a `migration.sql`
* Removed instances of the title field from `backend/services/implementations/userService.ts`, `backend/types.ts` and `backend/prisma/seed.ts` to compile

## Steps to test
1. Run it, review the changed files (pretty much just the removed lines)

## What should reviewers focus on?
* The changed files, since the site itself should appear unchanged

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by MatoPlus — CHANGES_REQUESTED** [review]
Backend changes looks good! I think we still need to the relevant client side types and calls.

Anything related to employee title should be deleted in the client. Just from a quick search, this includes:
- updating the PocCard component and it's usage to exclude use of title
- AccountForm `onEmployeeCreate` query makes a call by passing title, specifically, update the `CreateEmployeeDTO` type and make sure you can still create a employee via the account creation page via the `new-account` route
- update `EmployeeUserDTO` type to exclude title

**Review by twilkhoo — COMMENTED** [review]
Updated some frontend components, types, and some gql queries that had the employee title, plslmk if there's anything I should revert (or anything left)

**Review by neelismail01 — APPROVED** [review]
I think everything looks good now, feel free to merge!

**Review by MatoPlus — COMMENTED** [review]
merge conflicts 😩

**Review by MatoPlus — COMMENTED** [review]
seems to work, here's the graphql query i tested:
```

mutation {
  createEmployeeUser(employeeUser:{ firstName: "first", lastName: "last" email: "test3@foo.com", phoneNumber: "123456", emergencyContactName: "testname", emergencyContactPhone:"123456", emergencyContactEmail: "test2@foo.com", password:"passwd",branchId: 1, languages: [ENGLISH]}) {
    id
    firstName
  }
}
```

**Review by MatoPlus — APPROVED** [review]
LGTM, thanks for getting this in! I don't see any other instances of employee title to deprecate

**Pull request merged**
