### PR TITLE
Fix update user resolver to exclude branches as it is only changed by super admin via other resolvers

### LINKED ISSUE #664: Edit Volunteer/Employee shouldn't change branch
Users cannot change their branch info from the edit user resolver, use the update branch resolvers instead.

Tech:
Update edit user resolver to exclude branch update

### PR DESCRIPTION
**Pull request by MatoPlus**
## Ticket link

Closes #664 

## Implementation description
* Updated update user resolvers used by all users to exclude branches as it is only used in the edit profile account and does not have a field to update branches. We use the user management page which uses other branch update resolvers instead.

## Steps to test
1. Login to user with a branch, update profile, user branches still persist and is no longer cleared

## What should reviewers focus on?
* Correctness

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by briantu — DISMISSED** [review]
Getting an error when I click the "Save Changes" button in the edit account page for volunteer. @MatoPlus Can you see if this is related to your changes?

image

**Comment by twilkhoo** [comment]
Tested locally with Prisma Studio, everything works great! One question not of concern though- when creating accounts (in `createAccount` of `AccountForm.tsx`), branches is still set to [] but this makes sense since users only get assigned branches by super admins AFTER their account is created right?

**Comment by MatoPlus** [comment]
> Getting an error when I click the "Save Changes" button in the edit account page for volunteer. @MatoPlus Can you see if this is related to your changes?
> 
> image

Whoops, forgot to mention that you have to test locally since preview always use staging backend changes.

**Comment by MatoPlus** [comment]
> Tested locally with Prisma Studio, everything works great! One question not of concern though- when creating accounts (in `createAccount` of `AccountForm.tsx`), branches is still set to [] but this makes sense since users only get assigned branches by super admins AFTER their account is created right?

This is correct. It doesn't hurt to leave it in for a more complete "create" resolver.

**Comment by twilkhoo** [comment]
> > Tested locally with Prisma Studio, everything works great! One question not of concern though- when creating accounts (in `createAccount` of `AccountForm.tsx`), branches is still set to [] but this makes sense since users only get assigned branches by super admins AFTER their account is created right?
> 
> This is correct. It doesn't hurt to leave it in for a more complete "create" resolver.

Sounds good, LGTM!

**Review by twilkhoo — APPROVED** [review]

**Pull request merged**
